graph TD

Customer --> NessovoPlateForm
NessovoPlateForm --> Notification
NessovoPlateForm --> OIDCAuthentication

Customer["Customer"]
NessovoPlateForm["Nessovo Ticket Service Platform"]
Notification["Send Messages"]
OIDCAuthentication["Authentication Service"]

